### ISSUE TITLE
Question: What's the total memory size of the Mongo database once populated with all the 990 Forms?

### ISSUE THREAD

**Issue by adamlawrencium** [smartergiving/irs-990-fetch#3]
For 2016? For all years total?

Thanks!
Adam

**Comment by chadokruse** [comment]
It's large, but not unmanageably large. My use case requires splitting Form 990PF from the others (990 & 990EZ), so these numbers are based on those split collections:
 
**All Years: ~37GB**
31GB - 990 & 990EZ
6GB - 990PF

**2016: ~6.8GB**
5.6GB - 990 & 990EZ
1.2GB - 990PF

------------

PS - Depending on your hardware, you may find these updated fetch scripts useful:
https://github.com/grantmakers/grantmakers.github.io/tree/master/scripts/updates/fetch
